name: Apigee CI/CD Pipeline 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Authenticate with Google Cloud
        run: echo "$GCP_SA_KEY" > gcp-key.json
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Install Apigee CLI
        run: |
          go install github.com/apigee/apigeecli/v2@latest
          mkdir -p $HOME/bin
          mv $HOME/go/bin/apigeecli $HOME/bin/
          echo "$HOME/bin" >> $GITHUB_PATH
          apigeecli version

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven

      - name: Static Code Analysis (Linting & Testing)
        run: bash scripts/static-analysis.sh

      - name: Deploy Apigee Proxy using Maven
        run: mvn clean install apigee-edge:deploy -Ptest -Dapigee.config.options=update -Denv=test -Dorg=my-apigee-org

      - name: Deploy Shared Flow using Maven
        run: mvn clean install apigee-config:sharedflowdeploy -Ptest -Denv=test -Dorg=my-apigee-org

      - name: Deploy KVMs, Products, Target Servers
        run: bash scripts/deploy-configs.sh

      - name: Cleanup
        run: rm gcp-key.json

  rollback:
    runs-on: ubuntu-latest
    if: failure()
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Rollback Deployment
        run: bash scripts/rollback.sh
