name: Apigee CI/CD Pipeline 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Authenticate with Google Cloud
        run: echo "${{ secrets.GCP_SA_KEY }}" > gcp-key.json
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Install Apigee CLI
        run: |
           curl -LO https://github.com/apigee/apigeecli/releases/download/v2.9.1/apigeecli_v2.9.1_Linux_x86_64.zip
           unzip apigeecli_v2.9.1_Linux_x86_64.zip
           chmod +x apigeecli_v2.9.1_Linux_x86_64/apigeecli
           sudo mv apigeecli_v2.9.1_Linux_x86_64/apigeecli /usr/local/bin/
           apigeecli -v

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven

      - name: Run OWASP Dependency Check (Security Scan)
        run: mvn org.owasp:dependency-check-maven:check -DnvdApiKey=${{ secrets.NVD_API_KEY }}

      - name: Deploy Apigee Proxy using Maven
        run: mvn clean install apigee-edge:deploy -Ptest -Dapigee.config.options=update -Denv=test -Dorg=${{ secrets.APIGEE_ORG }}

      - name: Deploy Shared Flow using Maven
        run: mvn clean install apigee-config:sharedflowdeploy -Ptest -Denv=test -Dorg=${{ secrets.APIGEE_ORG }}

      - name: Deploy KVMs, Products, Target Servers
        run: bash scripts/deploy-configs.sh

      - name: Cleanup
        run: rm gcp-key.json

  rollback:
    runs-on: ubuntu-latest
    if: failure()
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Rollback Deployment
        run: bash scripts/rollback.sh
